name: Qrcode

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  qrcode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set directory permissions
      run: chmod -R 777 .

    - name: Build the docker-compose stack
      run: docker-compose up -d

    - name: Check running containers
      run: docker ps -a

    - name: Check docker logs
      run: docker-compose logs php

    - name: Run composer setup
      run: docker-compose exec -T php composer setup-ci

    - name: Run phpcs
      run: docker-compose exec -T php vendor/bin/phpcs

    - name: Run grumphp
      run: docker-compose exec -T php vendor/bin/grumphp run

    - name: Run phpunit
      run: docker-compose exec -T php vendor/bin/phpunit -c phpunit.xml
